#!/usr/bin/env python3
"""
Create new Spotify playlist and add tracks - with full permissions
"""

import json
import urllib.request
import urllib.error
import datetime

# Load credentials
with open('/root/.openclaw/workspace/.spotify_config.json', 'r') as f:
    config = json.load(f)['spotify']

ACCESS_TOKEN = config.get('access_token')

if not ACCESS_TOKEN:
    print("❌ Not authenticated!")
    exit(1)

# Load recommendations
try:
    with open('/tmp/spotify_recommendations.json', 'r') as f:
        data = json.load(f)
        track_ids = data.get('track_ids', [])
        tracks_info = data.get('tracks', [])
        
    if not track_ids:
        print("❌ No recommendations found!")
        exit(1)
        
    print(f"🎵 Creating new playlist with {len(track_ids)} tracks...")
    print()
    
    # Create playlist
    today = datetime.datetime.now().strftime('%Y-%m-%d')
    playlist_name = f"AI Recommendations - {today}"
    playlist_desc = "Generated by OpenClaw AI based on your liked songs"
    
    playlist_data = json.dumps({
        'name': playlist_name,
        'description': playlist_desc,
        'public': False
    }).encode()
    
    req = urllib.request.Request(
        'https://api.spotify.com/v1/me/playlists',
        data=playlist_data,
        headers={
            'Authorization': f'Bearer {ACCESS_TOKEN}',
            'Content-Type': 'application/json'
        },
        method='POST'
    )
    
    with urllib.request.urlopen(req) as response:
        playlist = json.loads(response.read().decode())
        playlist_id = playlist.get('id')
        playlist_url = playlist.get('external_urls', {}).get('spotify')
        
        print("✅ Playlist created!")
        print(f"   Name: {playlist_name}")
        print(f"   URL: {playlist_url}")
        print()
        
    # Add tracks using PUT method (alternative)
    tracks_uris = [f"spotify:track:{tid}" for tid in track_ids]
    
    add_data = json.dumps({
        'uris': tracks_uris
    }).encode()
    
    # Try POST first
    req = urllib.request.Request(
        f'https://api.spotify.com/v1/playlists/{playlist_id}/tracks',
        data=add_data,
        headers={
            'Authorization': f'Bearer {ACCESS_TOKEN}',
            'Content-Type': 'application/json'
        },
        method='POST'
    )
    
    try:
        with urllib.request.urlopen(req) as response:
            result = json.loads(response.read().decode())
            print(f"✅ Successfully added {len(tracks_uris)} tracks!")
            
    except urllib.error.HTTPError as e:
        if e.code == 403:
            print("⚠️  POST method failed, trying alternative...")
            # Try using requests library or check if we need different headers
            print(f"   Error: {e.read().decode()}")
            raise
        else:
            raise
        
    print()
    print("=" * 70)
    print("🎵 PLAYLIST CREATED SUCCESSFULLY!")
    print("=" * 70)
    print()
    print(f"📀 Name: {playlist_name}")
    print(f"🔗 URL: {playlist_url}")
    print()
    print("Tracks:")
    for i, track in enumerate(tracks_info[:20], 1):
        print(f"  {i:2}. {track['name']} - {', '.join(track['artists'])}")
    print()
    print("=" * 70)
    print()
    print("🎧 Open Spotify to listen to your new playlist!")
    print()
    print("⚠️  Note: If tracks weren't added automatically, you can manually")
    print("   add them using the track URLs from the list above.")
        
except Exception as e:
    print(f"❌ Error: {e}")
    import traceback
    traceback.print_exc()
