#!/usr/bin/env python3
"""
Create Spotify playlist with recommendations
"""

import json
import urllib.request
import urllib.parse
import datetime

# Load credentials
with open('/root/.openclaw/workspace/.spotify_config.json', 'r') as f:
    config = json.load(f)['spotify']

ACCESS_TOKEN = config.get('access_token')

if not ACCESS_TOKEN:
    print("❌ Not authenticated!")
    exit(1)

# Load recommendations
try:
    with open('/tmp/spotify_recommendations.json', 'r') as f:
        data = json.load(f)
        track_ids = data.get('track_ids', [])
        tracks_info = data.get('tracks', [])
        
    if not track_ids:
        print("❌ No recommendations found!")
        exit(1)
        
    print(f"🎵 Creating playlist with {len(track_ids)} tracks...")
    print()
    
    # Get user ID
    req = urllib.request.Request(
        'https://api.spotify.com/v1/me',
        headers={'Authorization': f'Bearer {ACCESS_TOKEN}'}
    )
    
    with urllib.request.urlopen(req) as response:
        user = json.loads(response.read().decode())
        user_id = user.get('id')
        
    # Create playlist
    today = datetime.datetime.now().strftime('%Y-%m-%d')
    playlist_name = f"OpenClaw Recommendations - {today}"
    playlist_desc = "Generated by OpenClaw based on your liked songs"
    
    playlist_data = json.dumps({
        'name': playlist_name,
        'description': playlist_desc,
        'public': False  # Private playlist
    }).encode()
    
    req = urllib.request.Request(
        f'https://api.spotify.com/v1/me/playlists',
        data=playlist_data,
        headers={
            'Authorization': f'Bearer {ACCESS_TOKEN}',
            'Content-Type': 'application/json'
        },
        method='POST'
    )
    
    with urllib.request.urlopen(req) as response:
        playlist = json.loads(response.read().decode())
        playlist_id = playlist.get('id')
        playlist_url = playlist.get('external_urls', {}).get('spotify')
        
        print("✅ Playlist created!")
        print(f"   Name: {playlist_name}")
        print(f"   URL: {playlist_url}")
        print()
        
    # Add tracks to playlist
    # Spotify allows max 100 tracks per request, we have 15 so we're good
    tracks_uris = [f"spotify:track:{tid}" for tid in track_ids]
    
    add_data = json.dumps({
        'uris': tracks_uris
    }).encode()
    
    req = urllib.request.Request(
        f'https://api.spotify.com/v1/playlists/{playlist_id}/tracks',
        data=add_data,
        headers={
            'Authorization': f'Bearer {ACCESS_TOKEN}',
            'Content-Type': 'application/json'
        },
        method='POST'
    )
    
    with urllib.request.urlopen(req) as response:
        result = json.loads(response.read().decode())
        
        print(f"✅ Added {len(tracks_uris)} tracks to playlist!")
        print()
        print("=" * 70)
        print("🎵 PLAYLIST CREATED SUCCESSFULLY!")
        print("=" * 70)
        print()
        print(f"📀 Name: {playlist_name}")
        print(f"🔗 URL: {playlist_url}")
        print()
        print("Tracks added:")
        for i, track in enumerate(tracks_info[:20], 1):
            print(f"  {i:2}. {track['name']} - {', '.join(track['artists'])}")
        print()
        print("=" * 70)
        print()
        print("💡 The playlist is now in your Spotify library!")
        print("   Open Spotify to listen 🎧")
        
except Exception as e:
    print(f"❌ Error: {e}")
    import traceback
    traceback.print_exc()
